/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
/**
 *
 * @author USER
 */
public class detail_budaya extends javax.swing.JFrame {
    private int selectedId;
    Connection conn;
    /**
     * Creates new form detail_budaya
     * @param selectedId
     */
    public detail_budaya(int selectedId) {
        initComponents();
        this.selectedId = selectedId;
        conn = koneksi.getConnection();
        
        loadDataDetailKebudayaan();
    }

    private void loadDataDetailKebudayaan() {
        String sql = "SELECT * FROM keragaman Where id = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)){
            ps.setInt(1, selectedId);
            try (ResultSet rs = ps.executeQuery()){
                if (rs.next()){
                    byte[] imageData = rs.getBytes("gambar");
                    if (imageData != null){
                        ImageIcon imageIcon = new ImageIcon(imageData);
                        Image scaledImage = imageIcon.getImage().getScaledInstance(lbl_gambar_detail_budaya.getWidth(), lbl_gambar_detail_budaya.getHeight(), Image.SCALE_SMOOTH);
                        lbl_gambar_detail_budaya.setIcon(new ImageIcon(scaledImage));
                    } else {
                        lbl_gambar_detail_budaya.setIcon(null);
                    }
                String judul = rs.getString("judul");
                lbl_judul_budaya.setText(judul);
                String artikel = rs.getString("artikel");
                lbl_artikel_detail_budaya.setText(artikel);
                }
            }
        } catch (SQLException e){
            System.out.println("Error Load Data :" + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_judul_budaya = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_gambar_detail_budaya = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_artikel_detail_budaya = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        btn_hapus_budaya = new javax.swing.JButton();
        btn_edit_budaya = new javax.swing.JButton();
        btn_posting = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        lbl_judul_budaya.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_judul_budaya.setText("WAYANG KULIT");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        lbl_gambar_detail_budaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wayang.jpg"))); // NOI18N
        jPanel2.add(lbl_gambar_detail_budaya);

        lbl_artikel_detail_budaya.setEditable(false);
        lbl_artikel_detail_budaya.setBackground(new java.awt.Color(255, 255, 255));
        lbl_artikel_detail_budaya.setColumns(20);
        lbl_artikel_detail_budaya.setRows(5);
        lbl_artikel_detail_budaya.setText("           Wayang kulit, terbuat dari kulit kerbau, diyakini sebagai embrio dari berbagai jenis wayang yang ada saat\nini. Ia dimainkan seorang dalang; diiringi musik gamelan yang dimainkan sekelompok nayaga (pemain gamelan)\ndan tembang yang dinyanyikan para pesinden. Setiap bagian dalam pementasan wayang kulit mempunyai\nsimbol dan makna filosofis yang kuat. Apalagi dari segi isi, cerita pewayangan selalu mengajarkan budi pekerti\nyang luhur, saling mencintai dan menghormati, sambil terkadang diselipkan kritik sosial dan peran lucu lewat\nadegan goro-goro.\n\n            Wayang kulit berasal dari dearah Jawa, dengan sejarah yang sangat panjang. Catatan tertua tentang\nwayang kulit atau wayang purwa tersua dalam Prasasti Kuti bertarikh 840 M dari Joho, Sidoarjo, Jawa Timur.\nPrasasti ini menyebut kata haringgit atau dalang. “Haringgit adalah bentuk halus dari kata ringgit.\nKata ini sampai sekarang masih ada dalam bahasa Jawa, yang berarti wayang,” catat Timbul Haryono, guru besar\narkeologi Universitas Gadjah Mada, dalam “Masyarakat Jawa Kuna dan Lingkungannya Pada Masa Borobudur”\ntermuat di 100 Tahun Pasca Pemugaran Candi Borobudur.\n\n             Pada masa itu, dalang memimpin dan memainkan pertunjukan wayang di lingkungan istana. Arkeolog\nDyah W. Dewi dalam “Kesenian Wayang Pada Masa Jawa Kuno dan Persebarannya di Asia” menyebut pertunjukan\nwayang mempunyai arti khusus. “Sehubungan dengan diselenggarakannya suatu upacara untuk memperingati\nsuatu kejadian,” catat Dyah, termuat di Pertemuan Arkeologi V.\n\n              Sebagian ahli pewayangan, semisal R.M. Mangkudimedja, menduga bentuk awal wayang tak seperti\nsekarang. Dulu wayang hanya tampak bagian depannya. Bahan dasar pembuatan wayang pun berbeda dari\nsekarang. Dulu wayang terbuat dari daun lontar, bukan kulit hewan ternak seperti sekarang.\n\n               Tapi selingkar ahli arkeologi lainnya membantah dugaan R.M. Mangkudimedja. Contohnya Soedarso\nSp. Dia meyakini wayang sudah terbuat dari kulit. Dia mendasarkan pandangannya pada isi Kakawin Arjunawiwaha\nanggitan Mpu Kanwa bertarikh 1036 M.\n\n                Tentang lakon dalam pertunjukan wayang kulit periode awal, hanya Prasasti Wukajani dari zaman\npemerintahan Raja Mataram bernama Dyah Balitung (907 M) yang menyebutnya cukup jelas. Prasasti Wukajani\nmenyebut mawayang bwat hyang atau pertunjukan wayang dengan lakon Bima Kumara. Kisah ini sempalan\ndari wiracarita Mahabharata yang bertutur tentang kegilaan Kicaka pada Drupadi.\n\n                 Keterangan tentang wayang kulit termaktub pula pada relief di candi-candi Jawa Timur abad ke-10\nseperti Candi Surawana, Candi Jago, Candi Tigawangi, dan Candi Panataran. Kehadiran wayang kulit dalam relief\ncandi di tiga tempat berbeda menunjukkan kesenian ini telah menyebar ke berbagai wilayah.\n\n                Kearifan lokal wayang kulit lahir, tumbuh, hidup di Indonesia, kemudian menyebar ke penjuru dunia.\nTidak salah jika Badan Perserikatan Bangsa-Bangsa untuk urusan Pendidikan, Ilmu Pengetahuan, dan Kebudayaan\n(Unesco) menetapkan wayang kulit sebagai warisan budaya dunia dari Indonesia.");
        jScrollPane1.setViewportView(lbl_artikel_detail_budaya);

        jPanel2.add(jScrollPane1);

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        btn_hapus_budaya.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus_budaya.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_hapus_budaya.setText("Hapus");
        btn_hapus_budaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_budayaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_hapus_budaya);

        btn_edit_budaya.setBackground(new java.awt.Color(255, 255, 0));
        btn_edit_budaya.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btn_edit_budaya.setText("Edit");
        btn_edit_budaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_budayaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_edit_budaya);

        btn_posting.setBackground(new java.awt.Color(0, 255, 0));
        btn_posting.setText("Post Baru");
        btn_posting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postingActionPerformed(evt);
            }
        });
        jPanel5.add(btn_posting);

        btn_kembali.setText("<");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_kembali)
                .addGap(182, 182, 182)
                .addComponent(lbl_judul_budaya)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_judul_budaya)
                    .addComponent(btn_kembali))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(550, 550, 550)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_postingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postingActionPerformed
        this.setVisible(false);
        create_budaya cb = new create_budaya();
        cb.setVisible(true);
        cb.pack();
        cb.setLocationRelativeTo(null);
        cb.setDefaultCloseOperation(create_budaya.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_postingActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        this.setVisible(false);
        kebudayaan kb = new kebudayaan();
        kb.setVisible(true);
        kb.pack();
        kb.setLocationRelativeTo(null);
        kb.setDefaultCloseOperation(kebudayaan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_edit_budayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_budayaActionPerformed
        this.setVisible(false);
        update_budaya ub = new update_budaya(selectedId);
        ub.setVisible(true);
        ub.pack();
        ub.setLocationRelativeTo(null);
        ub.setDefaultCloseOperation(update_budaya.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_edit_budayaActionPerformed

    private void btn_hapus_budayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_budayaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the data?", "Delete Confimation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION){
            try {
                String sql = "DELETE FROM keragaman WHERE id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, selectedId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Deleted Successfully");
                this.setVisible(false);
                
                kebudayaan kb = new kebudayaan();
                kb.setVisible(true);
                kb.pack();
                kb.setLocationRelativeTo(null);
                kb.setDefaultCloseOperation(kebudayaan.EXIT_ON_CLOSE);
            } catch(SQLException e){
                System.out.println("Error Delete Data:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_hapus_budayaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail_budaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail_budaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail_budaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail_budaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_budaya(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_budaya;
    private javax.swing.JButton btn_hapus_budaya;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_posting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lbl_artikel_detail_budaya;
    private javax.swing.JLabel lbl_gambar_detail_budaya;
    private javax.swing.JLabel lbl_judul_budaya;
    // End of variables declaration//GEN-END:variables
}
