/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author USER
 */
public class update_event extends javax.swing.JFrame {
    
    private int selectedId;
    Connection conn;
    /**
     * Creates new form update_event
     */
    public update_event(int selectedId) {
        initComponents();
        this.selectedId = selectedId;
        conn = koneksi.getConnection();
        
        loadDataDetailEvent();
        btn_update_event.addActionListener(e -> updateDataEvent());
    }
    
    private void loadDataDetailEvent() {
        String sql = "SELECT * FROM event Where id = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)){
            ps.setInt(1, selectedId);
            try (ResultSet rs = ps.executeQuery()){
                if (rs.next()){
                    byte[] imageData = rs.getBytes("gambar");
                    if (imageData != null){
                        ImageIcon imageIcon = new ImageIcon(imageData);
                        Image scaledImage = imageIcon.getImage().getScaledInstance(lbl_update_gambar_event.getWidth(), lbl_update_gambar_event.getHeight(), Image.SCALE_SMOOTH);
                        lbl_update_gambar_event.setIcon(new ImageIcon(scaledImage));
                    } else {
                        lbl_update_gambar_event.setIcon(null);
                    }
                    String judul = rs.getString("judul");
                    tf_update_judul_event.setText(judul);
                    String jadwal = rs.getString("jadwal");
                    txtarea_update_jadwal_event.setText(jadwal);
                }
            }
        } catch (SQLException e){
            System.out.println("Error Load Data :" + e.getMessage());
        }
    }
    
    private void updateDataEvent(){
        String sql = "UPDATE event SET gambar = ?, judul = ?, jadwal = ? WHERE id = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)){
            String imagePath = tf_update_gambar_event.getText();
            if (imagePath != null) {
                File imageFile = new File(imagePath);
                try (FileInputStream fis = new FileInputStream(imageFile)) {
                    byte[] imageData = fis.readAllBytes();
                    ps.setBytes(1, imageData);
                }
                
                long fileSize = imageFile.length();
                long maxSize = 10 * 1024 * 1024;
                
                if (fileSize > maxSize) {
                    JOptionPane.showMessageDialog(this, "File size is too large. Please select a smaller file.");
                    return;
                }
            } else {
                ps.setNull(1, java.sql.Types.LONGVARBINARY);
            }
            ps.setString(2, tf_update_judul_event.getText());
            ps.setString(3, txtarea_update_jadwal_event.getText());
            ps.setInt(4, selectedId);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Update Successfully");
        } catch (SQLException e){
            System.out.println("Error Update Data:" + e.getMessage());
        } catch (FileNotFoundException ex) {
            System.out.println("Error Reading File" + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Error Reading Image File:" + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_cancel_update_event = new javax.swing.JButton();
        btn_update_event = new javax.swing.JButton();
        btn_update_gambar_event = new javax.swing.JButton();
        tf_update_gambar_event = new javax.swing.JTextField();
        lbl_warning_update_event = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_update_jadwal_event = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tf_update_judul_event = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_update_gambar_event = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("EDIT EVENT");

        btn_cancel_update_event.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancel_update_event.setText("Cancel");
        btn_cancel_update_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel_update_eventActionPerformed(evt);
            }
        });

        btn_update_event.setBackground(new java.awt.Color(0, 255, 0));
        btn_update_event.setText("Update");
        btn_update_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_eventActionPerformed(evt);
            }
        });

        btn_update_gambar_event.setText("...");
        btn_update_gambar_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_gambar_eventActionPerformed(evt);
            }
        });

        tf_update_gambar_event.setEditable(false);

        lbl_warning_update_event.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_warning_update_event.setForeground(new java.awt.Color(255, 0, 51));
        lbl_warning_update_event.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtarea_update_jadwal_event.setColumns(20);
        txtarea_update_jadwal_event.setRows(5);
        jScrollPane1.setViewportView(txtarea_update_jadwal_event);

        jLabel6.setText("Jadwal");

        jLabel7.setText("Judul");

        jLabel1.setText("Gambar");

        lbl_update_gambar_event.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_update_gambar_event.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btn_cancel_update_event)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_event))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_warning_update_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(tf_update_gambar_event)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_update_gambar_event))
                                    .addComponent(lbl_update_gambar_event, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_update_judul_event, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel10)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_update_gambar_event, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update_gambar_event)
                            .addComponent(tf_update_gambar_event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_update_judul_event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_warning_update_event, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel_update_event)
                    .addComponent(btn_update_event))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_update_gambar_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_gambar_eventActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "webp", "gif", "bmp", "tiff");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            tf_update_gambar_event.setText(path);

            try {
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);

                int labelWidth =200;
                int labelHeight = 400;

                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();

                double scaleX = (double) labelWidth / (double) imageWidth;
                double scaleY = (double) labelHeight / (double) imageHeight;
                double scale = Math.min(scaleX, scaleY);

                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeight), Image.SCALE_SMOOTH);

                lbl_update_gambar_event.setIcon(new ImageIcon(scaledImage));
            } catch(IOException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_update_gambar_eventActionPerformed

    private void btn_update_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_eventActionPerformed
        String gambar = tf_update_gambar_event.getText();
        String judul = tf_update_judul_event.getText();
        String artikel = txtarea_update_jadwal_event.getText();

        if (gambar.isEmpty() || judul.isEmpty() || artikel.isEmpty()) {
            lbl_warning_update_event.setText("Data cannot be empty");
            return;
        }

        this.setVisible(false);
        detail_budaya db = new detail_budaya(selectedId);
        db.setVisible(true);
        db.pack();
        db.setLocationRelativeTo(null);
        db.setDefaultCloseOperation(detail_budaya.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_update_eventActionPerformed

    private void btn_cancel_update_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel_update_eventActionPerformed
        this.setVisible(false);
        kebudayaan kb = new kebudayaan();
        kb.setVisible(true);
        kb.pack();
        kb.setLocationRelativeTo(null);
        kb.setDefaultCloseOperation(kebudayaan.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_cancel_update_eventActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_event(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel_update_event;
    private javax.swing.JButton btn_update_event;
    private javax.swing.JButton btn_update_gambar_event;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_update_gambar_event;
    private javax.swing.JLabel lbl_warning_update_event;
    private javax.swing.JTextField tf_update_gambar_event;
    private javax.swing.JTextField tf_update_judul_event;
    private javax.swing.JTextArea txtarea_update_jadwal_event;
    // End of variables declaration//GEN-END:variables
}
